### ISSUE TITLE
Updating a cluster leads to API server downtime

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/kubernetes-on-aws#42]
First observation: the ELB healthcheck leads to ASG terminating a new instance because the `HealthCheckGracePeriod` defaults to 5 minutes and the master node sometimes takes longer than 5 minutes to come up :disappointed:

**Comment by hjacobs** [comment]
Another error during update:

```
node "ip-172-31-19-1.eu-west-1.compute.internal" cordoned
error: DaemonSet-managed pods (use --ignore-daemonsets to ignore): prometheus-node-exporter-7nx9i
Traceback (most recent call last):
  File "./cluster.py", line 459, in <module>
    cli()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "./cluster.py", line 303, in update
    perform_node_updates(stack_name, version, 'Worker', user_data_worker, variables)
  File "./cluster.py", line 420, in perform_node_updates
    drain_node(node_name, config)
  File "./cluster.py", line 353, in drain_node
    '--grace-period={}'.format(grace_period)])
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['kubectl', '--server', 'https://kube-1.x.example.org', '--token', 'xx', 'drain', 'ip-172-31-19-1.eu-west-1.compute.internal', '--force', '--delete-local-data', '--grace-period=30']' returned non-zero exit status 1

**Comment by hjacobs** [comment]
Update seems to work fine now and I did neither experience master nor app downtime:

```
$ ./cluster.py update kube 1 --force
Generating Cloud Formation template..You are deploying an internet-facing ELB that will be publicly accessible! You should have OAUTH2 and HTTPS in place!
 OK
Updating Cloud Formation stack kube-1.. OK
Waiting up to 594 more secs for stack kube-1 (UPDATE_IN_PROGRESS)..
Waiting up to 582 more secs for stack kube-1 (UPDATE_IN_PROGRESS)..
Waiting up to 572 more secs for stack kube-1 (UPDATE_IN_PROGRESS)..
Waiting up to 560 more secs for stack kube-1 (UPDATE_COMPLETE_CLEANUP_IN_PROGRESS)..
OK: Stack(s) kube-1 updated successfully.
Suspending scaling processes for kube-1-MasterAutoScaling-1NNN90TQW27F.. OK
Scaling up to 2 instances.. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . OK
Scaling down to 1 instances.. OK
Resuming scaling processes for kube-1-MasterAutoScaling-1NNN90TQW27F.. OK
Waiting for API server https://kube-1.xx.example.org.. OK
Suspending scaling processes for kube-1-WorkerAutoScaling-10URKFCX4HEIO.. OK
Scaling up to 4 instances.. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . OK
node "ip-172-31-19-210.eu-west-1.compute.internal" cordoned
WARNING: Deleting pods not managed by ReplicationController, ReplicaSet, Job, or DaemonSet: kube-proxy-ip-172-31-19-210.eu-west-1.compute.internal; Ignoring DaemonSet-managed pods: prometheus-node-exporter-7nx9i
node "ip-172-31-19-210.eu-west-1.compute.internal" drained
Terminating old instance i-bffbed28.. OK
Waiting for ASG to scale back to 4 instances.. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . OK
Scaling down to 3 instances.. OK
Resuming scaling processes for kube-1-WorkerAutoScaling-10URKFCX4HEIO.. OK
