### ISSUE TITLE
zmon-aws-agent has no permission to query dynamodb

### ISSUE THREAD

**Issue by linki** [zalando-incubator/kubernetes-on-aws#973]
seems like the zmon aws agent wants to collect dynamodb entities but doesn't have permission to do so:

```console
INFO:zmon-aws-agent:Trying to figure out region..
INFO:zmon-aws-agent:Using region: eu-central-1
INFO:zmon-aws-agent:Entity service URL: https://data-service.zmon.zalan.do/api/v1/entities/
INFO:zmon-aws-agent:Reading DNS data for hosted zones
INFO:tokens:Refreshing access token "uid"..
ERROR:zmon_aws_agent.aws:Got exception while listing dynamodb tables, IAM role has no access?
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/zmon_aws_agent-0.2-py3.6.egg/zmon_aws_agent/aws.py", line 606, in get_dynamodb_tables
    t = call_and_retry(ddb.describe_table, TableName=tn)['Table']
  File "/usr/local/lib/python3.6/dist-packages/zmon_aws_agent-0.2-py3.6.egg/zmon_aws_agent/common.py", line 31, in call_and_retry
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/botocore-1.9.0-py3.6.egg/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/botocore-1.9.0-py3.6.egg/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the DescribeTable operation: User: arn:aws:sts::123456789:assumed-role/kube-1-app-zmon/g12h3g2-kube-1-app-zmon is not authorized to perform: dynamodb:DescribeTable on resource: arn:aws:dynamodb:eu-central-1:123456789:table/live-attribute-intake-offsets
INFO:zmon-aws-agent:Removing 0 entities from ZMON
INFO:zmon-aws-agent:Found 0 removed entities from 35 entities (0 failed)
INFO:zmon-aws-agent:Adding 0 new entities in ZMON
INFO:zmon-aws-agent:Found 0 new entities from 35 entities (0 failed)
sleeping... 60 seconds
```

**Comment by mikkeloscar** [comment]
Fixed in #1227
